### ISSUE TITLE
Github GLMr out of sync with GRAN

### ISSUE THREAD

**Issue by jsta** [GLEON/GLMr#111]
The GRAN version is several commits behind yet has the same version number as the Github repo. Might consider incrementing the Github version number?

**Comment by lawinslow** [comment]
You mean the package version number? The lack of version change may indicate the commits didn't really change much. Looking at the commit history
https://github.com/GLEON/GLMr/commits/master

**Comment by jsta** [comment]
Not a critical issue it's just that I installed from GRAN and found it to be out of date yet had the same version number. Personally, like the strategy of incrementing the version in the development repo after release (http://r-pkgs.had.co.nz/release.html#post-release) so that its obvious whether or not the dev version is being run. I realize people have different thinking on this topic.

I didn't check the GRAN model version.

**Comment by lawinslow** [comment]
What do you mean by out of date? Was GLM old or was the package a different version number?

**Comment by jsta** [comment]
Sorry. I think there might be some confusion about whether we are talking about the version of GLM the compiled model or the version of `GLMr` the R package. 

I meant that the package info (docs) in the GRAN R package were behind the Github R package yet both R packages had the same version number. My suggestion was to increment the Github R package version in order to distinguish it from the GRAN R package on local machines. I wanted to check before submitting a PR because this versioning strategy is not shared by everyone.

I did not check the GRAN GLM compiled binary version.

**Comment by lawinslow** [comment]
Ah, got it. That's what I was asking. The priority in this package is really the GLM version, so I've probably been lax with the package version when nothing functional changes. You should submit a PR with a version increment!
